# Docker Compose configuration for Cedrina staging and production
# Connects to external PostgreSQL and Redis servers

services:
  app:
    image: cedrina:${APP_ENV:-production}
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    env_file:
      - .env.${APP_ENV:-production}
    environment:
      - APP_ENV=${APP_ENV:-production}
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - cedrina-network

networks:
  cedrina-network:
    driver: bridge
    name: cedrina-network