# Docker Compose configuration for Cedrina staging and production
# Connects to external PostgreSQL and Redis servers

services:
  app:
    image: cedrina:${APP_ENV:-production}
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    env_file:
      - .env.${APP_ENV:-production}
    environment:
      - APP_ENV=${APP_ENV:-production}
      - PYTHONPATH=/app:/app/src
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:8000/api/v1/health && PGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER -d $POSTGRES_DB -c 'SELECT 1 FROM alembic_version'"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 60s  # Allow time for migrations
    networks:
      - cedrina-network

networks:
  cedrina-network:
    driver: bridge
    name: cedrina-network