"""Add casbin_policies table for dynamic policy storage with versioning and audit logging

Revision ID: new_revision_id
Revises: ff19ad5772c3
Create Date: 2023-11-10 10:00:00.000000
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'new_revision_id'
down_revision = 'ff19ad5772c3'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casbin_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ptype', sa.String(), nullable=True),
    sa.Column('v0', sa.String(), nullable=True),
    sa.Column('v1', sa.String(), nullable=True),
    sa.Column('v2', sa.String(), nullable=True),
    sa.Column('v3', sa.String(), nullable=True),
    sa.Column('v4', sa.String(), nullable=True),
    sa.Column('v5', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False, default=1),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_casbin_policies_ptype'), 'casbin_policies', ['ptype'], unique=False)
    op.create_index(op.f('ix_casbin_policies_v0'), 'casbin_policies', ['v0'], unique=False)
    op.create_index(op.f('ix_casbin_policies_v1'), 'casbin_policies', ['v1'], unique=False)
    op.create_index(op.f('ix_casbin_policies_version'), 'casbin_policies', ['version'], unique=False)
    
    op.create_table('policy_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('operation', sa.String(), nullable=False),  # e.g., 'add', 'remove', 'update'
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('object', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('performed_by', sa.String(), nullable=True),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_audit_logs_performed_at'), 'policy_audit_logs', ['performed_at'], unique=False)
    op.create_index(op.f('ix_policy_audit_logs_performed_by'), 'policy_audit_logs', ['performed_by'], unique=False)
    op.create_index(op.f('ix_policy_audit_logs_operation'), 'policy_audit_logs', ['operation'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_audit_logs_operation'), table_name='policy_audit_logs')
    op.drop_index(op.f('ix_policy_audit_logs_performed_by'), table_name='policy_audit_logs')
    op.drop_index(op.f('ix_policy_audit_logs_performed_at'), table_name='policy_audit_logs')
    op.drop_table('policy_audit_logs')
    
    op.drop_index(op.f('ix_casbin_policies_version'), table_name='casbin_policies')
    op.drop_index(op.f('ix_casbin_policies_v1'), table_name='casbin_policies')
    op.drop_index(op.f('ix_casbin_policies_v0'), table_name='casbin_policies')
    op.drop_index(op.f('ix_casbin_policies_ptype'), table_name='casbin_policies')
    op.drop_table('casbin_policies')
    # ### end Alembic commands ### 