"""Add casbin_policies table for dynamic policy storage with versioning and audit logging

Revision ID: a1b2c3d4e5f6
Revises: dbade9aeb417
Create Date: 2023-11-10 10:00:00.000000
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'dbade9aeb417'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casbin_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ptype', sa.String(), nullable=True),
    sa.Column('v0', sa.String(), nullable=True),
    sa.Column('v1', sa.String(), nullable=True),
    sa.Column('v2', sa.String(), nullable=True),
    sa.Column('v3', sa.String(), nullable=True),
    sa.Column('v4', sa.String(), nullable=True),
    sa.Column('v5', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False, default=1),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_casbin_policies_ptype'), 'casbin_policies', ['ptype'], unique=False)
    op.create_index(op.f('ix_casbin_policies_v0'), 'casbin_policies', ['v0'], unique=False)
    op.create_index(op.f('ix_casbin_policies_v1'), 'casbin_policies', ['v1'], unique=False)
    op.create_index(op.f('ix_casbin_policies_version'), 'casbin_policies', ['version'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_casbin_policies_version'), table_name='casbin_policies')
    op.drop_index(op.f('ix_casbin_policies_v1'), table_name='casbin_policies')
    op.drop_index(op.f('ix_casbin_policies_v0'), table_name='casbin_policies')
    op.drop_index(op.f('ix_casbin_policies_ptype'), table_name='casbin_policies')
    op.drop_table('casbin_policies')
    # ### end Alembic commands ### 