"""Add casbin_rule and policy_audit_logs tables

Revision ID: dbade9aeb417
Revises: 21b29c875b37
Create Date: 2025-06-26 00:51:27.836978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbade9aeb417'
down_revision: Union[str, None] = '21b29c875b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('operation', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('object', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('performed_by', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['casbin_rule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('casbin_rule', 'ptype',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('casbin_rule', 'v0',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('casbin_rule', 'v1',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('casbin_rule', 'v2',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('casbin_rule', 'v3',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('casbin_rule', 'v4',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('casbin_rule', 'v5',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('casbin_rule', 'v5',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('casbin_rule', 'v4',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('casbin_rule', 'v3',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('casbin_rule', 'v2',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('casbin_rule', 'v1',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('casbin_rule', 'v0',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('casbin_rule', 'ptype',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_table('policy_audit_logs')
    # ### end Alembic commands ###
