"""Add casbin_rule and policy_audit_logs tables

Revision ID: dbade9aeb417
Revises: 21b29c875b37
Create Date: 2025-06-26 00:51:27.836978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dbade9aeb417'
down_revision: Union[str, None] = '21b29c875b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create casbin_rule table first
    op.create_table('casbin_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ptype', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('v0', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('v1', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('v2', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('v3', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('v4', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('v5', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create policy_audit_logs table with foreign key reference
    op.create_table('policy_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('operation', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('object', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('performed_by', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['casbin_rule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policy_audit_logs')
    op.drop_table('casbin_rule')
    # ### end Alembic commands ###
